### ISSUE TITLE
Overhaul colony info window

### ISSUE THREAD

**Issue by GoogleCodeExporter** [subchannel13/zvjezdojedac#38]
```
Version 0.4 requirement

Colony info window should be redone in a way to show only important data. 
Details such as how is something calculated should be available by clicking or 
hovering mouse over already shown data.

```

Original issue reported on code.google.com by `subchann...@gmail.com` on 27 Aug 2011 at 12:35

**Comment by subchannel13** [comment]
Task is invalid by now. GUI will be redone in the future, probably with GWEN.Net and system of tooltips and MoO 2 style of right clicking will be considered.
