### ISSUE TITLE
Game - GUI to MVC

### ISSUE THREAD

**Issue by GoogleCodeExporter** [subchannel13/zvjezdojedac#49]
```
Proposition for following:

Refactor code to MVC design pattern where the game is model and GUI is view.
```

Original issue reported on code.google.com by `subchann...@gmail.com` on 20 Feb 2012 at 9:58

**Comment by subchannel13** [comment]
Although it is still work in progress current rewrite adopts this pattern and it's more then 50% done. If there is a need to track this task, there should be a separate ticket for screen (form). Current ticket formulation is too broad for a single task.
