### ISSUE TITLE
Help or tooltips on forms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [subchannel13/zvjezdojedac#53]
```
Add either help buttons or tooltips to explain options on forms. Forms that 
need this:

- new game
- settings
- map setup
- player setup
- initial conditions
```

Original issue reported on code.google.com by `subchann...@gmail.com` on 9 May 2013 at 9:28

**Comment by subchannel13** [comment]
Feature request it rejected until the game becomes more fleshed out. Specifically when new GUI framework gets implemented. At some later point it will be reconsidered and broken to more specific tasks.
