### ISSUE TITLE
GUI options

### ISSUE THREAD

**Issue by GoogleCodeExporter** [subchannel13/zvjezdojedac#60]
```
Investigate and if possible implement:

1) Cursor locked to screen
2) Borderless window mode
3) Fullscreen mode
```

Original issue reported on code.google.com by `subchann...@gmail.com` on 26 Jan 2015 at 9:49

**Comment by subchannel13** [comment]
Feature request is rejected until the game becomes more fleshed out. At some later point it will be reconsidered.
